In [3]:
import numpy as np
np.array(1)

array(1)

In [4]:
type(np.array(1))

numpy.ndarray

In [21]:
ndarr_1 = np.array([1,2,3])
ndarr_1

array([1, 2, 3])

In [6]:
print(ndarr_1)

[1 2 3]


In [7]:
ndarr_1.dtype

dtype('int32')

In [8]:
ndarr_2 = np.array([1,2.0,3])
print(ndarr_2)

[1. 2. 3.]


In [9]:
ndarr_2.dtype

dtype('float64')

In [10]:
np.array([True, 1, 2.5, 'str', print])

array([True, 1, 2.5, 'str', <built-in function print>], dtype=object)

In [22]:
ndarr_1

array([1, 2, 3])

In [23]:
ndarr_1.shape

(3,)

In [12]:
ndarr_1.ndim

1

In [24]:
a = np.array(1)
a.ndim

0

In [25]:
a = [ [1,2,3], [4,5,6]]
a[1][0]

4

In [37]:
matrix = np.array([ [1,2,3], [4,5,6] ])
print(matrix)
print("ndim: {}" .format(matrix.ndim))
print("shape: {}".format(matrix.shape))

[[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)


In [38]:
tensor = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
print(tensor)
print("ndim: {}".format(tensor.ndim))
print("shape: {}".format(tensor.shape))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
ndim: 3
shape: (2, 2, 3)


In [39]:
tensor.size

12

In [40]:
arr = np.array( [[1,2,3], [2,4,6], [3,6,9]] )
print(arr)
print("ndim: {}".format(arr.ndim))
print("shape: {}".format(arr.shape))
print("dtype: {}".format(arr.dtype))
print("size: {}".format(arr.size))

[[1 2 3]
 [2 4 6]
 [3 6 9]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9


In [42]:
arr4 = np.array([[1,2,3,4], [5,6,7]])
print(arr4)
print("ndim: {}".format(arr4.ndim))
print("shape: {}".format(arr4.shape))
print("dtype: {}".format(arr4.dtype))
print("size: {}".format(arr4.size))

[list([1, 2, 3, 4]) list([5, 6, 7])]
ndim: 1
shape: (2,)
dtype: object
size: 2


C:\Users\Admin\AppData\Local\Temp\ipykernel_15148\594482708.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array([[1,2,3,4], [5,6,7]])


In [43]:
{1,1,1,2,2,3,3,5}

{1, 2, 3, 5}

In [44]:
np.array({1,1,1,2,2,3,3,5})

array({1, 2, 3, 5}, dtype=object)

In [45]:
np.array({'a':1, 'b':2})

array({'a': 1, 'b': 2}, dtype=object)

In [46]:
arr = np.array([ [[1,2], [3,4]],   [[5,6], [7,8]  ]])
print(arr)
arr[0]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[1, 2],
       [3, 4]])

In [48]:
arr[0][1][1]

4

In [49]:
list_ = [[[1,2], [3,4]], [[5,6],[7,8]]]
list_[0][1][1]

4

In [50]:
arr[0,1,1]

4

In [51]:
arr[0,1,1] = 5
arr

array([[[1, 2],
        [3, 5]],

       [[5, 6],
        [7, 8]]])