In [3]:
import numpy as np

In [5]:
np.arange(100,191,10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [6]:
np.arange(100,191,10).reshape(2,5)

array([[100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [10]:
np.arange(-2,2.5,0.5).reshape(3,3,-1)

array([[[-2. ],
        [-1.5],
        [-1. ]],

       [[-0.5],
        [ 0. ],
        [ 0.5]],

       [[ 1. ],
        [ 1.5],
        [ 2. ]]])

In [11]:
print(np.zeros(shape=(5,),dtype=np.int8))

[0 0 0 0 0]


In [12]:
print(np.zeros((5),int))

[0 0 0 0 0]


In [15]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
print(np.ones(shape=(5,),dtype = np.int8))

[1 1 1 1 1]


In [20]:
print(np.ones((5),int))

[1 1 1 1 1]


In [21]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Empty
#배열을 생성만 하고 값을 주지 않아 메모리에 저장되어 있던 기존 값이 저장될 수 있음

In [22]:
print(np.empty(shape=(10,),dtype=np.int32))

[1765089072        518 1828274352        518 1828274352        518
        257          0          0          0]


In [23]:
print(np.empty((2,5),np.int8))

[[1 1 1 1 0]
 [1 1 1 1 1]]


In [ ]:
#Zeros_like/Ones_like/Empy_like
# 입력받은 배열과 같은 shape. dtype의 배열 생성

In [24]:
matrix = np.arange(24).reshape(4,6)

In [25]:
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [27]:
matrix = np.arange(-2, 2, 0.2).reshape(2,10)

In [28]:
print(np.ones_like(matrix))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [29]:
matrix = np.arange(30).reshape(5,6)

In [30]:
print(np.empty_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [31]:
print(np.identity(5,dtype = np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [32]:
print(np.identity(2))

[[1. 0.]
 [0. 1.]]


In [33]:
print(np.eye(5,dtype = np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [34]:
print(np.eye(5,k=2))

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
print(np.eye(5,M=10,k=-1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [36]:
print(np.full((2,5),3))

[[3 3 3 3 3]
 [3 3 3 3 3]]


In [38]:
print(np.full((5,4),'a'))

[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


In [39]:
#Random.randint
#주어진 범위 안의 랜덤한 값을 뽑는 함수
#np.random.randint(range)

In [57]:
print(np.random.randint(6))

2


In [58]:
print(np.random.randint(1,20))

19


In [59]:
#Random.rand
#랜덤한 값으로 채워지는 배열
#표준 정규분포 난수를 shape 형태의 배열로 생성
#0~1사이의 값을 가짐

In [65]:
print(np.random.rand(3))

[0.07781831 0.14970176 0.58652128]


In [79]:
print(np.random.rand(3,2))

[[0.67520774 0.93701637]
 [0.18298746 0.38687827]
 [0.38375971 0.23274652]]


In [80]:
#Random.randn
#가우시안 표준 정규분포 난수를 shape형태의 배열로 생성

In [101]:
print(np.random.randn(3))

[0.55142231 1.28783175 0.71562053]


In [ ]:
#합(sum)

In [90]:
matrix = np.arange(1,7).reshape(2,3)

In [91]:
print(matrix.sum())

21


In [92]:
print(matrix.sum(axis=0)) # 행끼리 더하기(위 아래)

[5 7 9]


In [93]:
print(matrix.sum(axis=1))# 열끼리 더하기(좌 우)

[ 6 15]


In [98]:
#3차원 배열 합
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)
print("--------------------------------")
print(tensor.sum())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
--------------------------------
171


In [99]:
print(tensor.sum(axis=0))
print("--------------------------------")
print(tensor.sum(axis=1))
print("--------------------------------")
print(tensor.sum(axis=2))


[[21 24 27]
 [30 33 36]]
--------------------------------
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]
--------------------------------
[[ 6 15]
 [24 33]
 [42 51]]


In [100]:
#평균(mean)
#2차원 배열 평균
print(matrix.mean()) #전체 평균
print(matrix.mean(axis = 0)) #행끼리 평균(위 아래)
print(matrix.mean(axis=1))   #열끼리 평균(좌 우)

3.5
[2.5 3.5 4.5]
[2. 5.]


In [107]:
#list in for
[np.random.randint(1,101) for n in range(5)]

[70, 25, 96, 87, 69]

In [108]:
[ i if i % 2 == 0 else 0 for i in range(1,101)  ]

[0,
 2,
 0,
 4,
 0,
 6,
 0,
 8,
 0,
 10,
 0,
 12,
 0,
 14,
 0,
 16,
 0,
 18,
 0,
 20,
 0,
 22,
 0,
 24,
 0,
 26,
 0,
 28,
 0,
 30,
 0,
 32,
 0,
 34,
 0,
 36,
 0,
 38,
 0,
 40,
 0,
 42,
 0,
 44,
 0,
 46,
 0,
 48,
 0,
 50,
 0,
 52,
 0,
 54,
 0,
 56,
 0,
 58,
 0,
 60,
 0,
 62,
 0,
 64,
 0,
 66,
 0,
 68,
 0,
 70,
 0,
 72,
 0,
 74,
 0,
 76,
 0,
 78,
 0,
 80,
 0,
 82,
 0,
 84,
 0,
 86,
 0,
 88,
 0,
 90,
 0,
 92,
 0,
 94,
 0,
 96,
 0,
 98,
 0,
 100]

In [109]:
vector = np.random.randint(1,101,5)

In [110]:
vector

array([67, 43, 92, 72, 34])

In [111]:
np.sort(vector)

array([34, 43, 67, 72, 92])

In [112]:
#np.sort(vector)[start:end:step=-1]
np.sort(vector)[::-1]

array([92, 72, 67, 43, 34])

In [88]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

In [89]:
np.vstack( [ vector1, vector2 ] )

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
np.hstack( [ vector1, vector2 ] )

array([1, 2, 3, 4, 5, 6])

In [114]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

In [115]:
np.vstack([matrix1,matrix2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [118]:
np.hstack([matrix1,matrix2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [122]:
arr1 = np.array([[1,2,3],[4,5,6]])   # 2 x 3
arr2 = np.array([[7,8],[9,10]])      # 2 x 2

np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

In [123]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

In [124]:
np.concatenate([vector1, vector2], axis=0)

array([1, 2, 3, 4, 5, 6])

In [127]:
vector1 = np.array([1,2,3]).reshape(1,3)
vector2 = np.array([4,5,6]).reshape(1,3)

np.concatenate([vector1,vector2],axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
#다음 matrix와 vector를 하나의 배열로 합쳐보세요.
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([7,8,9])
vector1 = np.array([7,8,9]).reshape(1,3)

In [130]:
np.concatenate([matrix , vector1], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
np.vstack([matrix, vector])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
matrix.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [134]:
matrix.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [135]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [136]:
np.argmax(arr)

9

In [137]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
arr1 = np.random.rand(3,5)
arr1

array([[0.66864476, 0.56250906, 0.40051648, 0.77741903, 0.17266938],
       [0.80399017, 0.18917799, 0.22776555, 0.87381099, 0.79560503],
       [0.99757897, 0.18044477, 0.66822617, 0.74323242, 0.10794872]])

In [139]:
arr1.flatten()

array([0.66864476, 0.56250906, 0.40051648, 0.77741903, 0.17266938,
       0.80399017, 0.18917799, 0.22776555, 0.87381099, 0.79560503,
       0.99757897, 0.18044477, 0.66822617, 0.74323242, 0.10794872])

In [146]:
np.argmax(arr1)

10

In [145]:
np.argmin(arr1)

14

In [147]:
arr1

array([[0.66864476, 0.56250906, 0.40051648, 0.77741903, 0.17266938],
       [0.80399017, 0.18917799, 0.22776555, 0.87381099, 0.79560503],
       [0.99757897, 0.18044477, 0.66822617, 0.74323242, 0.10794872]])

In [148]:
np.argmax(arr1, axis = 0)

array([2, 0, 2, 1, 1], dtype=int64)

In [149]:
np.argmax(arr1, axis=1)

array([3, 3, 0], dtype=int64)

In [151]:
arr = np.random.rand(20)
arr

array([0.75440725, 0.19048719, 0.87566528, 0.87399418, 0.6267945 ,
       0.03103989, 0.95058794, 0.80666581, 0.15747294, 0.23117943,
       0.04834524, 0.27924209, 0.50478175, 0.87995282, 0.3128612 ,
       0.67813882, 0.3586261 , 0.46256721, 0.87797138, 0.91758991])

In [152]:
arr[np.argmax(arr)]

0.950587937327067

In [153]:
np.max(arr)

0.950587937327067