In [1]:
import numpy as np

In [7]:
data = np.loadtxt('./data/ex1_지역별전기요금.csv', delimiter=',', dtype = np.int32)

In [8]:
print(data[:5,:])

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


In [9]:
# 지역 구분, 가구수, 전기 사용량, 전기 요금

In [10]:
print(data.shape)

(17, 4)


In [11]:
print(data[:,:])

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]
 [      6  668623     364   35245]
 [      7  425659     344   32331]
 [      8  947300     366   36274]
 [      9 2737725     361   36569]
 [     10   49394     580   57091]
 [     11  323151     353   35470]
 [     12  734723     398   40049]
 [     13  726699     249   25120]
 [     14  634696     285   28556]
 [     15  258605     221   22180]
 [     16  742285     282   27901]
 [     17  584500     268   26899]]


In [12]:
print(np.unique(data[:,0]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [15]:
data[:,0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [16]:
len(np.unique(data[:,0]))

17

In [17]:
#데이터 확인하기
#데이터의 크기순 정렬 (argsort사용)

In [19]:
#중복된 최솟값을 가진 인덱스가 있어도 하나만 출력
np.argmin([1,2,6,3,0,0,10])

4

In [24]:
#배열로 인덱스를 정렬
arr_sort_index = np.argsort([1,2,6,3,0,0,10])

In [22]:
np.sort([1,2,6,3,0,0,10])

array([ 0,  0,  1,  2,  3,  6, 10])

In [25]:
arr = np.array([1,2,6,3,0,0,10])
arr

array([ 1,  2,  6,  3,  0,  0, 10])

In [26]:
arr[arr_sort_index]

array([ 0,  0,  1,  2,  3,  6, 10])

In [27]:
np.sort(data)

array([[      1,     273,   27177,  565082],
       [      2,     444,   45111, 2827233],
       [      3,     289,   29043, 1144913],
       [      4,     230,   22436, 1131034],
       [      5,     391,   38020,  380425],
       [      6,     364,   35245,  668623],
       [      7,     344,   32331,  425659],
       [      8,     366,   36274,  947300],
       [      9,     361,   36569, 2737725],
       [     10,     580,   49394,   57091],
       [     11,     353,   35470,  323151],
       [     12,     398,   40049,  734723],
       [     13,     249,   25120,  726699],
       [     14,     285,   28556,  634696],
       [     15,     221,   22180,  258605],
       [     16,     282,   27901,  742285],
       [     17,     268,   26899,  584500]])

In [28]:
#2차원 배열에서는 데이터가 섞이는 문제가 발생
np.sort(data, axis = 0)

array([[      1,   49394,     221,   22180],
       [      2,  258605,     230,   22436],
       [      3,  323151,     249,   25120],
       [      4,  380425,     268,   26899],
       [      5,  425659,     273,   27177],
       [      6,  565082,     282,   27901],
       [      7,  584500,     285,   28556],
       [      8,  634696,     289,   29043],
       [      9,  668623,     344,   32331],
       [     10,  726699,     353,   35245],
       [     11,  734723,     361,   35470],
       [     12,  742285,     364,   36274],
       [     13,  947300,     366,   36569],
       [     14, 1131034,     391,   38020],
       [     15, 1144913,     398,   40049],
       [     16, 2737725,     444,   45111],
       [     17, 2827233,     580,   57091]])

In [39]:
#그 문제를 해결한 것이 argsort()
data_sort = np.argsort(data[:,1])

array([ 1,  8,  2,  3,  7, 15, 11, 12,  5, 13, 16,  0,  6,  4, 10, 14,  9],
      dtype=int64)

In [31]:
data[data_sort]

array([[     10,   49394,     580,   57091],
       [     15,  258605,     221,   22180],
       [     11,  323151,     353,   35470],
       [      5,  380425,     391,   38020],
       [      7,  425659,     344,   32331],
       [      1,  565082,     273,   27177],
       [     17,  584500,     268,   26899],
       [     14,  634696,     285,   28556],
       [      6,  668623,     364,   35245],
       [     13,  726699,     249,   25120],
       [     12,  734723,     398,   40049],
       [     16,  742285,     282,   27901],
       [      8,  947300,     366,   36274],
       [      4, 1131034,     230,   22436],
       [      3, 1144913,     289,   29043],
       [      9, 2737725,     361,   36569],
       [      2, 2827233,     444,   45111]])

In [32]:
data[9]

array([   10, 49394,   580, 57091])

In [37]:
np.sort(data[:,1], axis = 0)[::-1]#Reverse

array([2827233, 2737725, 1144913, 1131034,  947300,  742285,  734723,
        726699,  668623,  634696,  584500,  565082,  425659,  380425,
        323151,  258605,   49394])

In [40]:
data_sort_reverse = np.argsort(data[:,1])[::-1]#Reverse

In [41]:
data[data_sort_reverse]

array([[      2, 2827233,     444,   45111],
       [      9, 2737725,     361,   36569],
       [      3, 1144913,     289,   29043],
       [      4, 1131034,     230,   22436],
       [      8,  947300,     366,   36274],
       [     16,  742285,     282,   27901],
       [     12,  734723,     398,   40049],
       [     13,  726699,     249,   25120],
       [      6,  668623,     364,   35245],
       [     14,  634696,     285,   28556],
       [     17,  584500,     268,   26899],
       [      1,  565082,     273,   27177],
       [      7,  425659,     344,   32331],
       [      5,  380425,     391,   38020],
       [     11,  323151,     353,   35470],
       [     15,  258605,     221,   22180],
       [     10,   49394,     580,   57091]])

In [53]:
#전국 대상 가구수의 합
sum(data[:,1])

14882047

In [44]:
np.sum(data, axis = 0)[1]

14882047

In [48]:
#가구당 평균 전력 사용량의 전국 평균값
data[:,2].mean()

335.1764705882353

In [52]:
round(data[:,2].mean(),2)

335.18

In [65]:
#가구당 평균 전력 사용량이 평균 이상인 지역과 대상 가구수 추출
avg_ = data[:,2].mean() # 가구당 평균 전력 사용량의 전국 평균
data[data[:,2] > avg_, :2]

array([[      2, 2827233],
       [      5,  380425],
       [      6,  668623],
       [      7,  425659],
       [      8,  947300],
       [      9, 2737725],
       [     10,   49394],
       [     11,  323151],
       [     12,  734723]])

In [66]:
data[data[:,2] > avg_][:, :2]

array([[      2, 2827233],
       [      5,  380425],
       [      6,  668623],
       [      7,  425659],
       [      8,  947300],
       [      9, 2737725],
       [     10,   49394],
       [     11,  323151],
       [     12,  734723]])