In [5]:
import numpy as np

In [44]:
data = np.loadtxt('./data/ex2_전년대비_시도별_교통사망사고.csv', 
                  delimiter= ',', skiprows = 1)#위에서부터 몇번째 행까지 지울때 사용

In [16]:
data[:5,:]

array([[ 2.014e+03,  1.000e+00,  2.180e+02,  4.800e+00, -9.000e+00,
        -4.000e+00],
       [ 2.014e+03,  2.000e+00,  8.720e+02,  1.900e+01, -4.500e+01,
        -4.900e+00],
       [ 2.014e+03,  3.000e+00,  4.010e+02,  8.700e+00, -4.500e+01,
        -1.010e+01],
       [ 2.014e+03,  4.000e+00,  4.640e+02,  1.010e+01, -4.100e+01,
        -8.100e+00],
       [ 2.014e+03,  5.000e+00,  9.900e+01,  2.200e+00, -5.000e+00,
        -4.800e+00]])

In [17]:
# 발생년도, 지역구분, 발생건수, 구성비, 증감수, 증감률

In [18]:
print(data[:3,[0,2,3]])

[[2014.   218.     4.8]
 [2014.   872.    19. ]
 [2014.   401.     8.7]]


In [57]:
print(data[7])

[2014.     8.   163.     3.6  -47.   -22.4]


In [54]:
print(data[data[:,1]==8])

[[2014.     8.   163.     3.6  -47.   -22.4]]


In [28]:
data[data[:,1] == 4]

array([], shape=(0, 6), dtype=float64)

In [29]:
np.sum(data, axis = 0)[2]

4583.0

In [30]:
data[: , 2].sum()

4583.0

In [31]:
data[:,2].mean()

269.5882352941176

In [ ]:
#위 데이터에서 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출해 봅시다.

In [46]:
data[data[:,4] == max(data[:,4])]

array([[2014. ,    6. ,  182. ,    4. ,   19. ,   11.7]])

In [47]:
data[np.argmax(data[:,4])]

array([2014. ,    6. ,  182. ,    4. ,   19. ,   11.7])

In [48]:
#교통사고 증감률이 가장 작은 지역의 모든 현황
data[np.argmin(data[:,5])]

array([2014. ,    8. ,  163. ,    3.6,  -47. ,  -22.4])

In [58]:
data

array([[ 2.014e+03,  1.000e+00,  2.180e+02,  4.800e+00, -9.000e+00,
        -4.000e+00],
       [ 2.014e+03,  2.000e+00,  8.720e+02,  1.900e+01, -4.500e+01,
        -4.900e+00],
       [ 2.014e+03,  3.000e+00,  4.010e+02,  8.700e+00, -4.500e+01,
        -1.010e+01],
       [ 2.014e+03,  4.000e+00,  4.640e+02,  1.010e+01, -4.100e+01,
        -8.100e+00],
       [ 2.014e+03,  5.000e+00,  9.900e+01,  2.200e+00, -5.000e+00,
        -4.800e+00],
       [ 2.014e+03,  6.000e+00,  1.820e+02,  4.000e+00,  1.900e+01,
         1.170e+01],
       [ 2.014e+03,  7.000e+00,  9.900e+01,  2.200e+00,  8.000e+00,
         8.800e+00],
       [ 2.014e+03,  8.000e+00,  1.630e+02,  3.600e+00, -4.700e+01,
        -2.240e+01],
       [ 2.014e+03,  9.000e+00,  3.860e+02,  8.400e+00,  1.400e+01,
         3.800e+00],
       [ 2.014e+03,  1.000e+01,  2.000e+01,  4.000e-01,  0.000e+00,
         0.000e+00],
       [ 2.014e+03,  1.100e+01,  1.030e+02,  2.200e+00, -1.600e+01,
        -1.340e+01],
       [ 2.014e+03,  

In [50]:
#위 데이터에서 사고 발생 건수가 400건 이상인 곳의 
#지역과 교통사고 발생건수(2), 증감수(4), 증감률(5)을 추출
data[data[:,2] >= 400][:,[1,2,4,5]]

array([[  2. , 872. , -45. ,  -4.9],
       [  3. , 401. , -45. , -10.1],
       [  4. , 464. , -41. ,  -8.1],
       [ 13. , 400. , -35. ,  -8. ]])