In [1]:
import numpy as np

In [2]:
n = np.random.randn(3,5)
n

array([[-1.50040391, -0.62130398,  0.64406401,  0.32664861, -2.09557273],
       [ 1.35658181,  0.00974365,  0.9449184 , -0.3576528 ,  0.91883543],
       [ 1.51322149,  1.11966105,  0.52467767, -0.53577192, -1.98750251]])

In [7]:
filepath = './n.npy'
n.tofile(filepath)

In [8]:
m = np.fromfile(filepath)
m

array([-1.50040391, -0.62130398,  0.64406401,  0.32664861, -2.09557273,
        1.35658181,  0.00974365,  0.9449184 , -0.3576528 ,  0.91883543,
        1.51322149,  1.11966105,  0.52467767, -0.53577192, -1.98750251])

In [9]:
n.shape, m.shape

((3, 5), (15,))

In [10]:
m.reshape(-1,5)

array([[-1.50040391, -0.62130398,  0.64406401,  0.32664861, -2.09557273],
       [ 1.35658181,  0.00974365,  0.9449184 , -0.3576528 ,  0.91883543],
       [ 1.51322149,  1.11966105,  0.52467767, -0.53577192, -1.98750251]])

In [14]:
np.save('./n1.npy',n)

In [15]:
m1 = np.load('./n1.npy')
m1

array([[-1.50040391, -0.62130398,  0.64406401,  0.32664861, -2.09557273],
       [ 1.35658181,  0.00974365,  0.9449184 , -0.3576528 ,  0.91883543],
       [ 1.51322149,  1.11966105,  0.52467767, -0.53577192, -1.98750251]])

In [16]:
m1.shape

(3, 5)

In [17]:
np.load('n.npy')

array([[-1.50040391, -0.62130398,  0.64406401,  0.32664861, -2.09557273],
       [ 1.35658181,  0.00974365,  0.9449184 , -0.3576528 ,  0.91883543],
       [ 1.51322149,  1.11966105,  0.52467767, -0.53577192, -1.98750251]])

In [18]:
np.fromfile('n1.npy')

array([ 1.87585069e-309,  1.17119999e+171,  5.22741680e-037,
        8.44740097e+252,  2.65141232e+180,  9.92152605e+247,
        2.16209968e+233,  1.05161974e-153,  6.01399921e-154,
        6.01347002e-154,  6.01347002e-154,  6.01347002e-154,
        6.01347002e-154,  6.01347002e-154,  6.01347002e-154,
        6.55490914e-260, -1.50040391e+000, -6.21303975e-001,
        6.44064014e-001,  3.26648611e-001, -2.09557273e+000,
        1.35658181e+000,  9.74365078e-003,  9.44918396e-001,
       -3.57652797e-001,  9.18835430e-001,  1.51322149e+000,
        1.11966105e+000,  5.24677669e-001, -5.35771920e-001,
       -1.98750251e+000])

In [19]:
np.savetxt('n.txt',n)

In [20]:
m = np.loadtxt('n.txt')
m

array([[-1.50040391, -0.62130398,  0.64406401,  0.32664861, -2.09557273],
       [ 1.35658181,  0.00974365,  0.9449184 , -0.3576528 ,  0.91883543],
       [ 1.51322149,  1.11966105,  0.52467767, -0.53577192, -1.98750251]])

In [21]:
n

array([[-1.50040391, -0.62130398,  0.64406401,  0.32664861, -2.09557273],
       [ 1.35658181,  0.00974365,  0.9449184 , -0.3576528 ,  0.91883543],
       [ 1.51322149,  1.11966105,  0.52467767, -0.53577192, -1.98750251]])

In [22]:
np.savetxt('n.csv',n, delimiter=',')

In [23]:
np.loadtxt('n.csv',dtype = str)

array(['-1.500403913151009183e+00,-6.213039750214642831e-01,6.440640140407144498e-01,3.266486111265996528e-01,-2.095572725267680347e+00',
       '1.356581813544904813e+00,9.743650779267486878e-03,9.449183959817999412e-01,-3.576527974807565680e-01,9.188354304414160234e-01',
       '1.513221492527669465e+00,1.119661046880438660e+00,5.246776686040705018e-01,-5.357719202612066800e-01,-1.987502507574513633e+00'],
      dtype='<U127')

In [24]:
np.savetxt('./data.csv',np.arange(1,26).reshape(5,5), delimiter=',')

In [25]:
arr1 = np.loadtxt('./06_data1.txt',dtype = str, delimiter='\t')
arr1

array([['1', '15', '14', '4'],
       ['12', '6', '7', '9'],
       ['8', '10', '11', '5'],
       ['13', '3', '2', '16']], dtype='<U2')

In [26]:
arr2 = np.loadtxt('./06_data2.txt',delimiter=',')
arr2

array([[ 1., 15., 14.,  4.],
       [12.,  6.,  7.,  9.],
       [ 8., 10., 11.,  5.],
       [13.,  3.,  2., 16.]])

In [27]:
arr = np.array([1,5,2,4,3])
arr

array([1, 5, 2, 4, 3])

In [28]:
np.sort(arr)

array([1, 2, 3, 4, 5])

In [29]:
np.argsort(arr)

array([0, 2, 4, 3, 1], dtype=int64)